# Generated by Django 3.2.9 on 2021-11-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_rename_due_date_task_due_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='details',
        ),
    ]
