# Generated by Django 3.2.9 on 2021-11-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_rename_content_task_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
