# Generated by Django 3.2.9 on 2021-11-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGeneration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referred_by',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile_number2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stream',
            field=models.CharField(choices=[('Mechanical Engg.', 'Mechanical Engg.'), ('Civil Engg.', 'Civil Engg.'), ('Electrical Engg.', 'Electrical Engg.'), ('Electronics Engg.', 'Electronics Engg.'), ('Computer Engg.', 'Computer Engg.'), ('Information Technology', 'Information Technology'), ('Other', 'Other')], max_length=32),
        ),
    ]
