# Generated by Django 3.2.9 on 2021-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGeneration', '0002_auto_20211117_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='school_college',
            field=models.CharField(default='MMCOE', max_length=64),
            preserve_default=False,
        ),
    ]
